from euler import *
from math import *
from itertools import permutations
from time import time,clock
t = time()
answer = 0

##tri = set(n*(n+1)/2 for n in range(2,100000))
##pen = set(n*(3*n-1)/2 for n in range(2,100000))
##hex =  [n*(2*n-1) for n in range(2,100000)]
##for i in hex:
##    if i in tri and i in pen:    #all hex are tri
##        print i
        
##l = 100000
##r = xrange(1, l)
##print     set( n*(n+1)/2   for n in r ) \
##        & set( n*(3*n-1)/2 for n in r ) \
##        & set( n*(2*n-1)   for n in r )

print max(set([n*(3*n-1)/2 for n in range(100000)])\
          &set([n*(2*n-1)for n in range(100000)]))

print 'time', time()-t

"""
Triangle, pentagonal, and hexagonal numbers are
generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also
pentagonal and hexagonal.
"""
